FROM ubuntu:20.04
# 安装界面无需交互
ENV DEBIAN_FRONTEND=noninteractive
ENV HOME /root
WORKDIR /root/
# ENV TZ=Asia/Shanghai # Centos

# 正常显示与输入中文
ENV LANG=C.UTF-8
SHELL [ "/bin/bash", "-c" ]

###########################################################
#                        基础设置                          #
###########################################################

# 修改时区 文件来源: /usr/share/zoneinfo/Asia/Shanghai
COPY etc/Shanghai /etc/localtime

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y make gcc gdb g++ build-essential cmake && \
    apt-get install -y clang clang-format clang-tidy clang-tools && \
    apt-get install -y wget bash zip rsync less && \
    apt-get install -y -f git vim tree htop zsh tmux xclip curl iputils-ping && \
    apt-get install -y language-pack-zh-hans

# 开发环境可以不清理
# apt clean && apt autoclean && apt -y autoremove && \
# rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# lrzsz: window / linux 互传文件:

###########################################################
#                        C++                              #
###########################################################
# bazel
# 参考: https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu
# buildifier 检查和格式化 WORKSPACE .bzl BUILD 文件
# 然后在setting.json中设置
# "bazel.buildifierExecutable": "/usr/local/bin/buildifier-linux-amd64",
# COPY cache/bazel-4.0.0-installer-linux-x86_64.sh /tmp
# COPY cache/buildifier-linux-amd64 /usr/local/bin
# RUN apt update &&
#     apt-get install -y openjdk-11-jdk &&
#     chmod +x /tmp/bazel-4.0.0-installer-linux-x86_64.sh &&
#     bash /tmp/bazel-4.0.0-installer-linux-x86_64.sh &&
#     chmod +x /usr/local/bin/buildifier-linux-amd64 &&
#     apt clean && rm -rf /tmp/*

###########################################################
#             tmux / zsh / htop / oh-my-zsh / fzf         #
###########################################################
COPY etc/tmux.conf .tmux.conf
COPY etc/zshrc .zshrc
COPY etc/htoprc .config/htop/htoprc
COPY etc/fd_ignore .config/fd/ignore
# 配置oh-my-zsh
COPY cache/ohmyzsh-master.zip /tmp
COPY cache/zsh-completions-master.zip /tmp
COPY cache/zsh-autosuggestions-master.zip /tmp
COPY cache/zsh-syntax-highlighting-master.zip /tmp
COPY cache/fzf-master.zip /tmp
COPY cache/fzf-0.26.0-linux_amd64.tar.gz /tmp
COPY cache/fd-musl_8.2.1_amd64.deb /tmp

RUN unzip -o /tmp/ohmyzsh-master.zip && \
    mv ohmyzsh-master /root/.oh-my-zsh/ && \
    chsh -s /bin/zsh && \
    unzip -o /tmp/zsh-completions-master.zip && \
    mv zsh-completions-master /root/.oh-my-zsh/custom/plugins/zsh-completions && \
    unzip -o /tmp/zsh-autosuggestions-master.zip && \
    mv zsh-autosuggestions-master /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions && \
    unzip -o /tmp/zsh-syntax-highlighting-master.zip && \
    mv zsh-syntax-highlighting-master /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting && \
    unzip -o /tmp/fzf-master.zip && \
    mv fzf-master ~/.fzf && \
    tar zxvf /tmp/fzf-0.26.0-linux_amd64.tar.gz -C /tmp && \
    mv /tmp/fzf ~/.fzf/bin && \
    chmod +x ~/.fzf/bin/fzf && \
    ~/.fzf/install --all && \
    dpkg -i /tmp/fd-musl_8.2.1_amd64.deb && \
    rm -rf /tmp/*

###########################################################
#                         vimrc                           #
###########################################################
# 两种配置供选择
# 1. 简单的vim，无插件
# COPY config/simple_vimrc .vimrc
# 使用 https://github.com/amix/vimrc.git
# 2. 好用的 vim 配置 amix/vimrc
# 中文教程: https://www.jianshu.com/p/352a132a1bfa
# 安装 2 会覆盖 1 中的vimrc
COPY cache/vimrc-master.zip /tmp
RUN tree && \
    # git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime && \
    # sh ~/.vim_runtime/install_awesome_vimrc.sh
    unzip -o /tmp/vimrc-master.zip && \
    mv vimrc-master ~/.vim_runtime && \ 
    sh ~/.vim_runtime/install_awesome_vimrc.sh && \
    rm -rf /tmp/*
# 覆盖默认配置
COPY etc/my_configs.vim /root/.vim_runtime/my_configs.vim

###########################################################
#                        git                              #
###########################################################
ARG GIT_USER_NAME
ARG GIT_USER_EMAIL
COPY etc/gitignore .gitignore
COPY etc/gitconfig .gitconfig
RUN git config --global user.name ${GIT_USER_NAME} && \
    git config --global user.email ${GIT_USER_EMAIL}

###########################################################
#                        ssh server                       #
###########################################################
# ssh 配置， 22 端口，用于vscode连接
# 参考 https://github.com/rastasheep/ubuntu-sshd/blob/ed6fffcaf5a49eccdf821af31c1594e3c3061010/18.04/Dockerfile
ARG ROOT_PASSWD
RUN apt update && \
    apt-get install -y openssh-server && \ 
    mkdir /var/run/sshd && \
    echo "root:${ROOT_PASSWD}" | chpasswd && \
    sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    mkdir .ssh && \
    echo "export VISIBLE=now" >>/etc/profile && \
    echo "Host *" >>/root/.ssh/config && \
    echo "    StrictHostKeyChecking no" >>/root/.ssh/config && \
    echo "    GlobalKnownHostsFile  /dev/null" >>/root/.ssh/config && \
    echo "    UserKnownHostsFile    /dev/null" >>/root/.ssh/config && \
    service ssh restart

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
CMD ["zsh"]
